#============ 数据库配置#======================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/people_manger
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root #请参照数据库加密使用，加密后的字符串替换掉xxxxxx,ENC为解密函数。


  #启动Spring MVC多文件上传
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: D:\Project\jdevtemplateboot\upload        #指定默认上传的文件夹
      max-file-size: 5MB      #限制单个文件最大大小
      max-request-size: 20MB  #限制所有文件最大大小
      resolve-lazily: false   #是否延迟多部件文件请求的参数和文件的解析

#
mybatis-plus:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#==================== 日志配合·标准  ===========================
logging:
  config: classpath:logback-spring-dev.xml




